# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/ui/ml_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1021, 529)
        self.tabs_widget = QtWidgets.QTabWidget(Dialog)
        self.tabs_widget.setGeometry(QtCore.QRect(20, 20, 981, 521))
        self.tabs_widget.setObjectName("tabs_widget")
        self.dataset_load_tab = QtWidgets.QWidget()
        self.dataset_load_tab.setObjectName("dataset_load_tab")
        self.load_file_pushButton = QtWidgets.QPushButton(self.dataset_load_tab)
        self.load_file_pushButton.setGeometry(QtCore.QRect(220, 0, 113, 32))
        self.load_file_pushButton.setObjectName("load_file_pushButton")
        self.dataset_tableWidget = QtWidgets.QTableWidget(self.dataset_load_tab)
        self.dataset_tableWidget.setGeometry(QtCore.QRect(10, 40, 941, 411))
        self.dataset_tableWidget.setToolTip("")
        self.dataset_tableWidget.setToolTipDuration(30000)
        self.dataset_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataset_tableWidget.setObjectName("dataset_tableWidget")
        self.dataset_tableWidget.setColumnCount(0)
        self.dataset_tableWidget.setRowCount(0)
        self.tabs_widget.addTab(self.dataset_load_tab, "")
        self.visualise_tab = QtWidgets.QWidget()
        self.visualise_tab.setObjectName("visualise_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.visualise_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 171, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.columnSelection_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.columnSelection_comboBox.setObjectName("columnSelection_comboBox")
        self.verticalLayout.addWidget(self.columnSelection_comboBox)
        self.plot_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.plot_radioButton.setObjectName("plot_radioButton")
        self.verticalLayout.addWidget(self.plot_radioButton)
        self.boxplot_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.boxplot_radioButton.setObjectName("boxplot_radioButton")
        self.verticalLayout.addWidget(self.boxplot_radioButton)
        self.histogram_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.histogram_radioButton.setObjectName("histogram_radioButton")
        self.verticalLayout.addWidget(self.histogram_radioButton)
        self.columnSummary_textBrowser = QtWidgets.QTextBrowser(self.visualise_tab)
        self.columnSummary_textBrowser.setGeometry(QtCore.QRect(19, 160, 251, 161))
        self.columnSummary_textBrowser.setObjectName("columnSummary_textBrowser")
        self.dataVisualisePlot_widget = MplWidget(self.visualise_tab)
        self.dataVisualisePlot_widget.setGeometry(QtCore.QRect(339, 10, 621, 471))
        self.dataVisualisePlot_widget.setObjectName("dataVisualisePlot_widget")
        self.tabs_widget.addTab(self.visualise_tab, "")
        self.pre_process_tab = QtWidgets.QWidget()
        self.pre_process_tab.setObjectName("pre_process_tab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.pre_process_tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 661, 221))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.numeric_scaling_horizontalLayout = QtWidgets.QHBoxLayout()
        self.numeric_scaling_horizontalLayout.setObjectName("numeric_scaling_horizontalLayout")
        self.numeric_scaling_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.numeric_scaling_checkBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.numeric_scaling_checkBox.setObjectName("numeric_scaling_checkBox")
        self.numeric_scaling_horizontalLayout.addWidget(self.numeric_scaling_checkBox)
        self.verticalLayout_5.addLayout(self.numeric_scaling_horizontalLayout)
        self.remove_duplicates_horizontalLayout = QtWidgets.QHBoxLayout()
        self.remove_duplicates_horizontalLayout.setObjectName("remove_duplicates_horizontalLayout")
        self.remove_duplicates_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_duplicates_checkBox.sizePolicy().hasHeightForWidth())
        self.remove_duplicates_checkBox.setSizePolicy(sizePolicy)
        self.remove_duplicates_checkBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.remove_duplicates_checkBox.setObjectName("remove_duplicates_checkBox")
        self.remove_duplicates_horizontalLayout.addWidget(self.remove_duplicates_checkBox)
        self.verticalLayout_5.addLayout(self.remove_duplicates_horizontalLayout)
        self.remove_outliers_horizontalLayout = QtWidgets.QHBoxLayout()
        self.remove_outliers_horizontalLayout.setObjectName("remove_outliers_horizontalLayout")
        self.remove_outliers_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.remove_outliers_checkBox.setMaximumSize(QtCore.QSize(380, 16777215))
        self.remove_outliers_checkBox.setObjectName("remove_outliers_checkBox")
        self.remove_outliers_horizontalLayout.addWidget(self.remove_outliers_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.remove_outliers_horizontalLayout.addItem(spacerItem)
        self.outliers_treshold_horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_5)
        self.outliers_treshold_horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outliers_treshold_horizontalSlider.setMinimum(10)
        self.outliers_treshold_horizontalSlider.setMaximum(90)
        self.outliers_treshold_horizontalSlider.setSingleStep(5)
        self.outliers_treshold_horizontalSlider.setPageStep(5)
        self.outliers_treshold_horizontalSlider.setProperty("value", 20)
        self.outliers_treshold_horizontalSlider.setSliderPosition(20)
        self.outliers_treshold_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.outliers_treshold_horizontalSlider.setObjectName("outliers_treshold_horizontalSlider")
        self.remove_outliers_horizontalLayout.addWidget(self.outliers_treshold_horizontalSlider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.remove_outliers_horizontalLayout.addItem(spacerItem1)
        self.outliers_treshold_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.outliers_treshold_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.outliers_treshold_label.setObjectName("outliers_treshold_label")
        self.remove_outliers_horizontalLayout.addWidget(self.outliers_treshold_label)
        self.treshold_sigma_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treshold_sigma_label.sizePolicy().hasHeightForWidth())
        self.treshold_sigma_label.setSizePolicy(sizePolicy)
        self.treshold_sigma_label.setMaximumSize(QtCore.QSize(380, 16777215))
        self.treshold_sigma_label.setObjectName("treshold_sigma_label")
        self.remove_outliers_horizontalLayout.addWidget(self.treshold_sigma_label)
        self.verticalLayout_5.addLayout(self.remove_outliers_horizontalLayout)
        self.replace_value_horizontalLayout = QtWidgets.QHBoxLayout()
        self.replace_value_horizontalLayout.setObjectName("replace_value_horizontalLayout")
        self.replace_values_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.replace_values_checkBox.setMaximumSize(QtCore.QSize(380, 16777215))
        self.replace_values_checkBox.setObjectName("replace_values_checkBox")
        self.replace_value_horizontalLayout.addWidget(self.replace_values_checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.replace_value_horizontalLayout.addItem(spacerItem2)
        self.pre_process_replacing_stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_process_replacing_stackedWidget.sizePolicy().hasHeightForWidth())
        self.pre_process_replacing_stackedWidget.setSizePolicy(sizePolicy)
        self.pre_process_replacing_stackedWidget.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pre_process_replacing_stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pre_process_replacing_stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pre_process_replacing_stackedWidget.setObjectName("pre_process_replacing_stackedWidget")
        self.page_numeric = QtWidgets.QWidget()
        self.page_numeric.setObjectName("page_numeric")
        self.replaced_value_lineEdit = QtWidgets.QLineEdit(self.page_numeric)
        self.replaced_value_lineEdit.setGeometry(QtCore.QRect(0, 0, 183, 21))
        self.replaced_value_lineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.replaced_value_lineEdit.setObjectName("replaced_value_lineEdit")
        self.pre_process_replacing_stackedWidget.addWidget(self.page_numeric)
        self.page_categorical = QtWidgets.QWidget()
        self.page_categorical.setObjectName("page_categorical")
        self.replaced_value_comboBox = QtWidgets.QComboBox(self.page_categorical)
        self.replaced_value_comboBox.setGeometry(QtCore.QRect(0, 0, 104, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replaced_value_comboBox.sizePolicy().hasHeightForWidth())
        self.replaced_value_comboBox.setSizePolicy(sizePolicy)
        self.replaced_value_comboBox.setMaximumSize(QtCore.QSize(16777215, 26))
        self.replaced_value_comboBox.setObjectName("replaced_value_comboBox")
        self.pre_process_replacing_stackedWidget.addWidget(self.page_categorical)
        self.replace_value_horizontalLayout.addWidget(self.pre_process_replacing_stackedWidget)
        self.label_in = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in.sizePolicy().hasHeightForWidth())
        self.label_in.setSizePolicy(sizePolicy)
        self.label_in.setMaximumSize(QtCore.QSize(380, 21))
        self.label_in.setObjectName("label_in")
        self.replace_value_horizontalLayout.addWidget(self.label_in)
        self.replace_columnSelection_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.replace_columnSelection_comboBox.setObjectName("replace_columnSelection_comboBox")
        self.replace_value_horizontalLayout.addWidget(self.replace_columnSelection_comboBox)
        self.label_with = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_with.sizePolicy().hasHeightForWidth())
        self.label_with.setSizePolicy(sizePolicy)
        self.label_with.setMaximumSize(QtCore.QSize(380, 21))
        self.label_with.setObjectName("label_with")
        self.replace_value_horizontalLayout.addWidget(self.label_with)
        self.replacing_value_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.replacing_value_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.replacing_value_lineEdit.setObjectName("replacing_value_lineEdit")
        self.replace_value_horizontalLayout.addWidget(self.replacing_value_lineEdit)
        self.verticalLayout_5.addLayout(self.replace_value_horizontalLayout)
        self.pre_process_dataset_tableWidget = QtWidgets.QTableWidget(self.pre_process_tab)
        self.pre_process_dataset_tableWidget.setGeometry(QtCore.QRect(10, 330, 591, 121))
        self.pre_process_dataset_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.pre_process_dataset_tableWidget.setObjectName("pre_process_dataset_tableWidget")
        self.pre_process_dataset_tableWidget.setColumnCount(0)
        self.pre_process_dataset_tableWidget.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.pre_process_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 270, 791, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.replace_value_horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.replace_value_horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.replace_value_horizontalLayout_2.setObjectName("replace_value_horizontalLayout_2")
        self.filter_values_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.filter_values_checkBox.setMaximumSize(QtCore.QSize(380, 16777215))
        self.filter_values_checkBox.setObjectName("filter_values_checkBox")
        self.replace_value_horizontalLayout_2.addWidget(self.filter_values_checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(27, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.replace_value_horizontalLayout_2.addItem(spacerItem3)
        self.filter_columnSelection_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_columnSelection_comboBox.sizePolicy().hasHeightForWidth())
        self.filter_columnSelection_comboBox.setSizePolicy(sizePolicy)
        self.filter_columnSelection_comboBox.setObjectName("filter_columnSelection_comboBox")
        self.replace_value_horizontalLayout_2.addWidget(self.filter_columnSelection_comboBox)
        self.filter_operator_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.filter_operator_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filter_operator_comboBox.setObjectName("filter_operator_comboBox")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.replace_value_horizontalLayout_2.addWidget(self.filter_operator_comboBox)
        self.pre_process_filtering_stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_process_filtering_stackedWidget.sizePolicy().hasHeightForWidth())
        self.pre_process_filtering_stackedWidget.setSizePolicy(sizePolicy)
        self.pre_process_filtering_stackedWidget.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pre_process_filtering_stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pre_process_filtering_stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pre_process_filtering_stackedWidget.setObjectName("pre_process_filtering_stackedWidget")
        self.page_numeric_2 = QtWidgets.QWidget()
        self.page_numeric_2.setObjectName("page_numeric_2")
        self.filtering_dataset_value_lineEdit = QtWidgets.QLineEdit(self.page_numeric_2)
        self.filtering_dataset_value_lineEdit.setGeometry(QtCore.QRect(0, 0, 231, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtering_dataset_value_lineEdit.sizePolicy().hasHeightForWidth())
        self.filtering_dataset_value_lineEdit.setSizePolicy(sizePolicy)
        self.filtering_dataset_value_lineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.filtering_dataset_value_lineEdit.setObjectName("filtering_dataset_value_lineEdit")
        self.pre_process_filtering_stackedWidget.addWidget(self.page_numeric_2)
        self.page_categorical_2 = QtWidgets.QWidget()
        self.page_categorical_2.setObjectName("page_categorical_2")
        self.filtering_dataset_value_comboBox = QtWidgets.QComboBox(self.page_categorical_2)
        self.filtering_dataset_value_comboBox.setGeometry(QtCore.QRect(0, 0, 104, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtering_dataset_value_comboBox.sizePolicy().hasHeightForWidth())
        self.filtering_dataset_value_comboBox.setSizePolicy(sizePolicy)
        self.filtering_dataset_value_comboBox.setMaximumSize(QtCore.QSize(16777215, 26))
        self.filtering_dataset_value_comboBox.setObjectName("filtering_dataset_value_comboBox")
        self.pre_process_filtering_stackedWidget.addWidget(self.page_categorical_2)
        self.replace_value_horizontalLayout_2.addWidget(self.pre_process_filtering_stackedWidget)
        self.preprocess_replace_listWidget = QtWidgets.QListWidget(self.pre_process_tab)
        self.preprocess_replace_listWidget.setGeometry(QtCore.QRect(680, 140, 281, 61))
        self.preprocess_replace_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.preprocess_replace_listWidget.setObjectName("preprocess_replace_listWidget")
        self.preprocess_filter_listWidget = QtWidgets.QListWidget(self.pre_process_tab)
        self.preprocess_filter_listWidget.setGeometry(QtCore.QRect(740, 360, 221, 81))
        self.preprocess_filter_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.preprocess_filter_listWidget.setObjectName("preprocess_filter_listWidget")
        self.remove_replace_value_pushButton = QtWidgets.QPushButton(self.pre_process_tab)
        self.remove_replace_value_pushButton.setGeometry(QtCore.QRect(712, 200, 211, 32))
        self.remove_replace_value_pushButton.setObjectName("remove_replace_value_pushButton")
        self.remove_filter_rule_pushButton = QtWidgets.QPushButton(self.pre_process_tab)
        self.remove_filter_rule_pushButton.setGeometry(QtCore.QRect(800, 450, 131, 32))
        self.remove_filter_rule_pushButton.setObjectName("remove_filter_rule_pushButton")
        self.addrule_filter_value_pushButton = QtWidgets.QPushButton(self.pre_process_tab)
        self.addrule_filter_value_pushButton.setGeometry(QtCore.QRect(610, 330, 113, 32))
        self.addrule_filter_value_pushButton.setObjectName("addrule_filter_value_pushButton")
        self.addrule_replace_value_pushButton = QtWidgets.QPushButton(self.pre_process_tab)
        self.addrule_replace_value_pushButton.setGeometry(QtCore.QRect(560, 240, 113, 32))
        self.addrule_replace_value_pushButton.setObjectName("addrule_replace_value_pushButton")
        self.label_in_2 = QtWidgets.QLabel(self.pre_process_tab)
        self.label_in_2.setGeometry(QtCore.QRect(760, 110, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in_2.sizePolicy().hasHeightForWidth())
        self.label_in_2.setSizePolicy(sizePolicy)
        self.label_in_2.setMaximumSize(QtCore.QSize(380, 21))
        self.label_in_2.setObjectName("label_in_2")
        self.label_in_3 = QtWidgets.QLabel(self.pre_process_tab)
        self.label_in_3.setGeometry(QtCore.QRect(810, 330, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in_3.sizePolicy().hasHeightForWidth())
        self.label_in_3.setSizePolicy(sizePolicy)
        self.label_in_3.setMaximumSize(QtCore.QSize(380, 21))
        self.label_in_3.setObjectName("label_in_3")
        self.tabs_widget.addTab(self.pre_process_tab, "")
        self.inputoutput_tab = QtWidgets.QWidget()
        self.inputoutput_tab.setObjectName("inputoutput_tab")
        self.listWidget = QtWidgets.QListWidget(self.inputoutput_tab)
        self.listWidget.setGeometry(QtCore.QRect(290, 130, 256, 192))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label_2 = QtWidgets.QLabel(self.inputoutput_tab)
        self.label_2.setGeometry(QtCore.QRect(280, 65, 291, 41))
        self.label_2.setObjectName("label_2")
        self.tabs_widget.addTab(self.inputoutput_tab, "")
        self.model_selection_tab = QtWidgets.QWidget()
        self.model_selection_tab.setObjectName("model_selection_tab")
        self.tabs_widget.addTab(self.model_selection_tab, "")
        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.tabs_widget.addTab(self.train_tab, "")
        self.test_tab = QtWidgets.QWidget()
        self.test_tab.setObjectName("test_tab")
        self.tabs_widget.addTab(self.test_tab, "")

        self.retranslateUi(Dialog)
        self.tabs_widget.setCurrentIndex(0)
        self.pre_process_replacing_stackedWidget.setCurrentIndex(1)
        self.pre_process_filtering_stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Machine Learning Generic Modeller"))
        self.load_file_pushButton.setText(_translate("Dialog", "Load File"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.dataset_load_tab), _translate("Dialog", "Dataset Load"))
        self.plot_radioButton.setText(_translate("Dialog", "Plot"))
        self.boxplot_radioButton.setText(_translate("Dialog", "Boxplot"))
        self.histogram_radioButton.setText(_translate("Dialog", "Histogram"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.visualise_tab), _translate("Dialog", "Visualise"))
        self.numeric_scaling_checkBox.setText(_translate("Dialog", "Numeric Scaling "))
        self.remove_duplicates_checkBox.setText(_translate("Dialog", "Remove Dulpicate"))
        self.remove_outliers_checkBox.setText(_translate("Dialog", "Remove Outliers"))
        self.outliers_treshold_label.setText(_translate("Dialog", "2.0"))
        self.treshold_sigma_label.setText(_translate("Dialog", " σ"))
        self.replace_values_checkBox.setText(_translate("Dialog", "Replace Values"))
        self.label_in.setText(_translate("Dialog", "in"))
        self.label_with.setText(_translate("Dialog", "with"))
        self.filter_values_checkBox.setText(_translate("Dialog", "Filter"))
        self.filter_operator_comboBox.setItemText(0, _translate("Dialog", "Equal"))
        self.filter_operator_comboBox.setItemText(1, _translate("Dialog", "Not equal"))
        self.filter_operator_comboBox.setItemText(2, _translate("Dialog", "Less than"))
        self.filter_operator_comboBox.setItemText(3, _translate("Dialog", "Less than or equal to"))
        self.filter_operator_comboBox.setItemText(4, _translate("Dialog", "Greater than"))
        self.filter_operator_comboBox.setItemText(5, _translate("Dialog", "Greater than or equal to"))
        self.remove_replace_value_pushButton.setText(_translate("Dialog", "Remove Selected"))
        self.remove_filter_rule_pushButton.setText(_translate("Dialog", "Remove Selected"))
        self.addrule_filter_value_pushButton.setText(_translate("Dialog", "Add Rule"))
        self.addrule_replace_value_pushButton.setText(_translate("Dialog", "Add Rule"))
        self.label_in_2.setText(_translate("Dialog", "Replacing Rules"))
        self.label_in_3.setText(_translate("Dialog", "Filtering Rules"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.pre_process_tab), _translate("Dialog", "Pre-Process"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "aaaa"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "bbbb"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "cccc"))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "ddddd"))
        item = self.listWidget.item(4)
        item.setText(_translate("Dialog", "eeee"))
        item = self.listWidget.item(5)
        item.setText(_translate("Dialog", "ffff"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Dialog", "QListWidget With Multiple Selection Enabled"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.inputoutput_tab), _translate("Dialog", "Input/Output"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.model_selection_tab), _translate("Dialog", "Model Selction"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.train_tab), _translate("Dialog", "Train"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.test_tab), _translate("Dialog", "Test"))

from controller import MplWidget
