# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../resources/ui/ml_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 524)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/ML.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tabs_widget = QtWidgets.QTabWidget(Dialog)
        self.tabs_widget.setGeometry(QtCore.QRect(10, 10, 981, 531))
        self.tabs_widget.setObjectName("tabs_widget")
        self.dataset_load_tab = QtWidgets.QWidget()
        self.dataset_load_tab.setObjectName("dataset_load_tab")
        self.load_file_pushButton = QtWidgets.QPushButton(self.dataset_load_tab)
        self.load_file_pushButton.setGeometry(QtCore.QRect(220, 0, 113, 32))
        self.load_file_pushButton.setObjectName("load_file_pushButton")
        self.dataset_tableWidget = QtWidgets.QTableWidget(self.dataset_load_tab)
        self.dataset_tableWidget.setGeometry(QtCore.QRect(10, 40, 951, 411))
        self.dataset_tableWidget.setToolTip("")
        self.dataset_tableWidget.setToolTipDuration(30000)
        self.dataset_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataset_tableWidget.setObjectName("dataset_tableWidget")
        self.dataset_tableWidget.setColumnCount(0)
        self.dataset_tableWidget.setRowCount(0)
        self.tabs_widget.addTab(self.dataset_load_tab, "")
        self.visualise_tab = QtWidgets.QWidget()
        self.visualise_tab.setObjectName("visualise_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.visualise_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 171, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.columnSelection_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.columnSelection_comboBox.setObjectName("columnSelection_comboBox")
        self.verticalLayout.addWidget(self.columnSelection_comboBox)
        self.plot_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.plot_radioButton.setObjectName("plot_radioButton")
        self.verticalLayout.addWidget(self.plot_radioButton)
        self.boxplot_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.boxplot_radioButton.setObjectName("boxplot_radioButton")
        self.verticalLayout.addWidget(self.boxplot_radioButton)
        self.histogram_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.histogram_radioButton.setObjectName("histogram_radioButton")
        self.verticalLayout.addWidget(self.histogram_radioButton)
        self.columnSummary_textBrowser = QtWidgets.QTextBrowser(self.visualise_tab)
        self.columnSummary_textBrowser.setGeometry(QtCore.QRect(19, 160, 251, 161))
        self.columnSummary_textBrowser.setObjectName("columnSummary_textBrowser")
        self.dataVisualisePlot_widget = MplWidget(self.visualise_tab)
        self.dataVisualisePlot_widget.setGeometry(QtCore.QRect(339, 10, 621, 471))
        self.dataVisualisePlot_widget.setObjectName("dataVisualisePlot_widget")
        self.tabs_widget.addTab(self.visualise_tab, "")
        self.pre_process_tab = QtWidgets.QWidget()
        self.pre_process_tab.setObjectName("pre_process_tab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.pre_process_tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 661, 221))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.numeric_scaling_horizontalLayout = QtWidgets.QHBoxLayout()
        self.numeric_scaling_horizontalLayout.setObjectName("numeric_scaling_horizontalLayout")
        self.numeric_scaling_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.numeric_scaling_checkBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.numeric_scaling_checkBox.setObjectName("numeric_scaling_checkBox")
        self.numeric_scaling_horizontalLayout.addWidget(self.numeric_scaling_checkBox)
        self.verticalLayout_5.addLayout(self.numeric_scaling_horizontalLayout)
        self.remove_duplicates_horizontalLayout = QtWidgets.QHBoxLayout()
        self.remove_duplicates_horizontalLayout.setObjectName("remove_duplicates_horizontalLayout")
        self.remove_duplicates_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_duplicates_checkBox.sizePolicy().hasHeightForWidth())
        self.remove_duplicates_checkBox.setSizePolicy(sizePolicy)
        self.remove_duplicates_checkBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.remove_duplicates_checkBox.setObjectName("remove_duplicates_checkBox")
        self.remove_duplicates_horizontalLayout.addWidget(self.remove_duplicates_checkBox)
        self.verticalLayout_5.addLayout(self.remove_duplicates_horizontalLayout)
        self.remove_outliers_horizontalLayout = QtWidgets.QHBoxLayout()
        self.remove_outliers_horizontalLayout.setObjectName("remove_outliers_horizontalLayout")
        self.remove_outliers_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.remove_outliers_checkBox.setMaximumSize(QtCore.QSize(380, 16777215))
        self.remove_outliers_checkBox.setObjectName("remove_outliers_checkBox")
        self.remove_outliers_horizontalLayout.addWidget(self.remove_outliers_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.remove_outliers_horizontalLayout.addItem(spacerItem)
        self.outliers_treshold_horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_5)
        self.outliers_treshold_horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.outliers_treshold_horizontalSlider.setMinimum(10)
        self.outliers_treshold_horizontalSlider.setMaximum(90)
        self.outliers_treshold_horizontalSlider.setSingleStep(5)
        self.outliers_treshold_horizontalSlider.setPageStep(5)
        self.outliers_treshold_horizontalSlider.setProperty("value", 20)
        self.outliers_treshold_horizontalSlider.setSliderPosition(20)
        self.outliers_treshold_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.outliers_treshold_horizontalSlider.setObjectName("outliers_treshold_horizontalSlider")
        self.remove_outliers_horizontalLayout.addWidget(self.outliers_treshold_horizontalSlider)
        spacerItem1 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.remove_outliers_horizontalLayout.addItem(spacerItem1)
        self.outliers_treshold_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.outliers_treshold_label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.outliers_treshold_label.setObjectName("outliers_treshold_label")
        self.remove_outliers_horizontalLayout.addWidget(self.outliers_treshold_label)
        self.treshold_sigma_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treshold_sigma_label.sizePolicy().hasHeightForWidth())
        self.treshold_sigma_label.setSizePolicy(sizePolicy)
        self.treshold_sigma_label.setMaximumSize(QtCore.QSize(380, 16777215))
        self.treshold_sigma_label.setObjectName("treshold_sigma_label")
        self.remove_outliers_horizontalLayout.addWidget(self.treshold_sigma_label)
        self.verticalLayout_5.addLayout(self.remove_outliers_horizontalLayout)
        self.replace_value_horizontalLayout = QtWidgets.QHBoxLayout()
        self.replace_value_horizontalLayout.setObjectName("replace_value_horizontalLayout")
        self.replace_values_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.replace_values_checkBox.setMaximumSize(QtCore.QSize(380, 16777215))
        self.replace_values_checkBox.setObjectName("replace_values_checkBox")
        self.replace_value_horizontalLayout.addWidget(self.replace_values_checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(27, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.replace_value_horizontalLayout.addItem(spacerItem2)
        self.pre_process_replacing_stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_process_replacing_stackedWidget.sizePolicy().hasHeightForWidth())
        self.pre_process_replacing_stackedWidget.setSizePolicy(sizePolicy)
        self.pre_process_replacing_stackedWidget.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pre_process_replacing_stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pre_process_replacing_stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pre_process_replacing_stackedWidget.setObjectName("pre_process_replacing_stackedWidget")
        self.page_numeric = QtWidgets.QWidget()
        self.page_numeric.setObjectName("page_numeric")
        self.replaced_value_lineEdit = QtWidgets.QLineEdit(self.page_numeric)
        self.replaced_value_lineEdit.setGeometry(QtCore.QRect(0, 0, 183, 21))
        self.replaced_value_lineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.replaced_value_lineEdit.setObjectName("replaced_value_lineEdit")
        self.pre_process_replacing_stackedWidget.addWidget(self.page_numeric)
        self.page_categorical = QtWidgets.QWidget()
        self.page_categorical.setObjectName("page_categorical")
        self.replaced_value_comboBox = QtWidgets.QComboBox(self.page_categorical)
        self.replaced_value_comboBox.setGeometry(QtCore.QRect(0, 0, 150, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replaced_value_comboBox.sizePolicy().hasHeightForWidth())
        self.replaced_value_comboBox.setSizePolicy(sizePolicy)
        self.replaced_value_comboBox.setMaximumSize(QtCore.QSize(16777215, 26))
        self.replaced_value_comboBox.setObjectName("replaced_value_comboBox")
        self.pre_process_replacing_stackedWidget.addWidget(self.page_categorical)
        self.replace_value_horizontalLayout.addWidget(self.pre_process_replacing_stackedWidget)
        self.label_in = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in.sizePolicy().hasHeightForWidth())
        self.label_in.setSizePolicy(sizePolicy)
        self.label_in.setMaximumSize(QtCore.QSize(380, 21))
        self.label_in.setObjectName("label_in")
        self.replace_value_horizontalLayout.addWidget(self.label_in)
        self.replace_columnSelection_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        self.replace_columnSelection_comboBox.setObjectName("replace_columnSelection_comboBox")
        self.replace_value_horizontalLayout.addWidget(self.replace_columnSelection_comboBox)
        self.label_with = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_with.sizePolicy().hasHeightForWidth())
        self.label_with.setSizePolicy(sizePolicy)
        self.label_with.setMaximumSize(QtCore.QSize(380, 21))
        self.label_with.setObjectName("label_with")
        self.replace_value_horizontalLayout.addWidget(self.label_with)
        self.replacing_value_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.replacing_value_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.replacing_value_lineEdit.setObjectName("replacing_value_lineEdit")
        self.replace_value_horizontalLayout.addWidget(self.replacing_value_lineEdit)
        self.verticalLayout_5.addLayout(self.replace_value_horizontalLayout)
        self.pre_process_dataset_tableWidget = QtWidgets.QTableWidget(self.pre_process_tab)
        self.pre_process_dataset_tableWidget.setGeometry(QtCore.QRect(10, 330, 591, 121))
        self.pre_process_dataset_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.pre_process_dataset_tableWidget.setObjectName("pre_process_dataset_tableWidget")
        self.pre_process_dataset_tableWidget.setColumnCount(0)
        self.pre_process_dataset_tableWidget.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.pre_process_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 270, 791, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.replace_value_horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.replace_value_horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.replace_value_horizontalLayout_2.setObjectName("replace_value_horizontalLayout_2")
        self.filter_values_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.filter_values_checkBox.setMaximumSize(QtCore.QSize(380, 16777215))
        self.filter_values_checkBox.setObjectName("filter_values_checkBox")
        self.replace_value_horizontalLayout_2.addWidget(self.filter_values_checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(27, 21, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.replace_value_horizontalLayout_2.addItem(spacerItem3)
        self.filter_columnSelection_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_columnSelection_comboBox.sizePolicy().hasHeightForWidth())
        self.filter_columnSelection_comboBox.setSizePolicy(sizePolicy)
        self.filter_columnSelection_comboBox.setObjectName("filter_columnSelection_comboBox")
        self.replace_value_horizontalLayout_2.addWidget(self.filter_columnSelection_comboBox)
        self.filter_operator_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.filter_operator_comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.filter_operator_comboBox.setObjectName("filter_operator_comboBox")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.filter_operator_comboBox.addItem("")
        self.replace_value_horizontalLayout_2.addWidget(self.filter_operator_comboBox)
        self.pre_process_filtering_stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pre_process_filtering_stackedWidget.sizePolicy().hasHeightForWidth())
        self.pre_process_filtering_stackedWidget.setSizePolicy(sizePolicy)
        self.pre_process_filtering_stackedWidget.setMaximumSize(QtCore.QSize(16777215, 26))
        self.pre_process_filtering_stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pre_process_filtering_stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pre_process_filtering_stackedWidget.setObjectName("pre_process_filtering_stackedWidget")
        self.page_numeric_2 = QtWidgets.QWidget()
        self.page_numeric_2.setObjectName("page_numeric_2")
        self.filtering_dataset_value_lineEdit = QtWidgets.QLineEdit(self.page_numeric_2)
        self.filtering_dataset_value_lineEdit.setGeometry(QtCore.QRect(0, 0, 220, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtering_dataset_value_lineEdit.sizePolicy().hasHeightForWidth())
        self.filtering_dataset_value_lineEdit.setSizePolicy(sizePolicy)
        self.filtering_dataset_value_lineEdit.setMaximumSize(QtCore.QSize(16777215, 26))
        self.filtering_dataset_value_lineEdit.setObjectName("filtering_dataset_value_lineEdit")
        self.pre_process_filtering_stackedWidget.addWidget(self.page_numeric_2)
        self.page_categorical_2 = QtWidgets.QWidget()
        self.page_categorical_2.setObjectName("page_categorical_2")
        self.filtering_dataset_value_comboBox = QtWidgets.QComboBox(self.page_categorical_2)
        self.filtering_dataset_value_comboBox.setGeometry(QtCore.QRect(0, 0, 200, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filtering_dataset_value_comboBox.sizePolicy().hasHeightForWidth())
        self.filtering_dataset_value_comboBox.setSizePolicy(sizePolicy)
        self.filtering_dataset_value_comboBox.setMaximumSize(QtCore.QSize(16777215, 26))
        self.filtering_dataset_value_comboBox.setObjectName("filtering_dataset_value_comboBox")
        self.pre_process_filtering_stackedWidget.addWidget(self.page_categorical_2)
        self.replace_value_horizontalLayout_2.addWidget(self.pre_process_filtering_stackedWidget)
        self.preprocess_replace_listWidget = QtWidgets.QListWidget(self.pre_process_tab)
        self.preprocess_replace_listWidget.setGeometry(QtCore.QRect(680, 140, 281, 61))
        self.preprocess_replace_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.preprocess_replace_listWidget.setObjectName("preprocess_replace_listWidget")
        self.preprocess_filter_listWidget = QtWidgets.QListWidget(self.pre_process_tab)
        self.preprocess_filter_listWidget.setGeometry(QtCore.QRect(620, 360, 341, 81))
        self.preprocess_filter_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.preprocess_filter_listWidget.setObjectName("preprocess_filter_listWidget")
        self.addrule_filter_value_pushButton = QtWidgets.QPushButton(self.pre_process_tab)
        self.addrule_filter_value_pushButton.setGeometry(QtCore.QRect(610, 320, 113, 32))
        self.addrule_filter_value_pushButton.setObjectName("addrule_filter_value_pushButton")
        self.addrule_replace_value_pushButton = QtWidgets.QPushButton(self.pre_process_tab)
        self.addrule_replace_value_pushButton.setGeometry(QtCore.QRect(560, 240, 113, 32))
        self.addrule_replace_value_pushButton.setObjectName("addrule_replace_value_pushButton")
        self.label_in_2 = QtWidgets.QLabel(self.pre_process_tab)
        self.label_in_2.setGeometry(QtCore.QRect(760, 110, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in_2.sizePolicy().hasHeightForWidth())
        self.label_in_2.setSizePolicy(sizePolicy)
        self.label_in_2.setMaximumSize(QtCore.QSize(380, 21))
        self.label_in_2.setObjectName("label_in_2")
        self.label_in_3 = QtWidgets.QLabel(self.pre_process_tab)
        self.label_in_3.setGeometry(QtCore.QRect(810, 330, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_in_3.sizePolicy().hasHeightForWidth())
        self.label_in_3.setSizePolicy(sizePolicy)
        self.label_in_3.setMaximumSize(QtCore.QSize(380, 21))
        self.label_in_3.setObjectName("label_in_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.pre_process_tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(690, 210, 271, 32))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.remove_replace_value_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.remove_replace_value_pushButton.setObjectName("remove_replace_value_pushButton")
        self.horizontalLayout_6.addWidget(self.remove_replace_value_pushButton)
        self.clear_replace_value_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.clear_replace_value_pushButton.setObjectName("clear_replace_value_pushButton")
        self.horizontalLayout_6.addWidget(self.clear_replace_value_pushButton)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.pre_process_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(710, 440, 224, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.remove_filter_rule_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.remove_filter_rule_pushButton.setObjectName("remove_filter_rule_pushButton")
        self.horizontalLayout_7.addWidget(self.remove_filter_rule_pushButton)
        self.clear_filter_rule_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.clear_filter_rule_pushButton.setObjectName("clear_filter_rule_pushButton")
        self.horizontalLayout_7.addWidget(self.clear_filter_rule_pushButton)
        self.tabs_widget.addTab(self.pre_process_tab, "")
        self.model_selection_tab = QtWidgets.QWidget()
        self.model_selection_tab.setObjectName("model_selection_tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.model_selection_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(31, 20, 941, 471))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.regression_selection_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.regression_selection_radioButton.setChecked(True)
        self.regression_selection_radioButton.setAutoExclusive(True)
        self.regression_selection_radioButton.setObjectName("regression_selection_radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.regression_selection_radioButton)
        self.horizontalLayout_8.addWidget(self.regression_selection_radioButton)
        self.classification_selection_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.classification_selection_radioButton.setAutoExclusive(True)
        self.classification_selection_radioButton.setObjectName("classification_selection_radioButton")
        self.buttonGroup.addButton(self.classification_selection_radioButton)
        self.horizontalLayout_8.addWidget(self.classification_selection_radioButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.regression_and_classification_stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget_2)
        self.regression_and_classification_stackedWidget.setObjectName("regression_and_classification_stackedWidget")
        self.page_regression = QtWidgets.QWidget()
        self.page_regression.setObjectName("page_regression")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_regression)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, -10, 931, 431))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.nn_regression_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.nn_regression_radioButton.setChecked(True)
        self.nn_regression_radioButton.setObjectName("nn_regression_radioButton")
        self.verticalLayout_9.addWidget(self.nn_regression_radioButton)
        self.svm_regression_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.svm_regression_radioButton.setObjectName("svm_regression_radioButton")
        self.verticalLayout_9.addWidget(self.svm_regression_radioButton)
        self.randomforest_regression_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.randomforest_regression_radioButton.setObjectName("randomforest_regression_radioButton")
        self.verticalLayout_9.addWidget(self.randomforest_regression_radioButton)
        self.gradientboosting_regression_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.gradientboosting_regression_radioButton.setObjectName("gradientboosting_regression_radioButton")
        self.verticalLayout_9.addWidget(self.gradientboosting_regression_radioButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_9.addWidget(self.line_2)
        self.regression_parameters_stackedWidget = QtWidgets.QStackedWidget(self.horizontalLayoutWidget)
        self.regression_parameters_stackedWidget.setObjectName("regression_parameters_stackedWidget")
        self.nn_regression_page = QtWidgets.QWidget()
        self.nn_regression_page.setObjectName("nn_regression_page")
        self.layoutWidget1 = QtWidgets.QWidget(self.nn_regression_page)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 721, 381))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.reg_nn_hidden_layers_label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_hidden_layers_label.sizePolicy().hasHeightForWidth())
        self.reg_nn_hidden_layers_label.setSizePolicy(sizePolicy)
        self.reg_nn_hidden_layers_label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_nn_hidden_layers_label.setObjectName("reg_nn_hidden_layers_label")
        self.verticalLayout_11.addWidget(self.reg_nn_hidden_layers_label)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.reg_nn_layers_horizontalSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.reg_nn_layers_horizontalSlider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.reg_nn_layers_horizontalSlider.setMinimum(1)
        self.reg_nn_layers_horizontalSlider.setMaximum(50)
        self.reg_nn_layers_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.reg_nn_layers_horizontalSlider.setObjectName("reg_nn_layers_horizontalSlider")
        self.horizontalLayout_19.addWidget(self.reg_nn_layers_horizontalSlider)
        self.reg_nn_layers_label = QtWidgets.QLabel(self.layoutWidget1)
        self.reg_nn_layers_label.setObjectName("reg_nn_layers_label")
        self.horizontalLayout_19.addWidget(self.reg_nn_layers_label)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.reg_nn_layers_tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.reg_nn_layers_tableWidget.setMaximumSize(QtCore.QSize(235, 16777215))
        self.reg_nn_layers_tableWidget.setObjectName("reg_nn_layers_tableWidget")
        self.reg_nn_layers_tableWidget.setColumnCount(1)
        self.reg_nn_layers_tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.reg_nn_layers_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reg_nn_layers_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.reg_nn_layers_tableWidget.setItem(0, 0, item)
        self.reg_nn_layers_tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_11.addWidget(self.reg_nn_layers_tableWidget)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_17.addWidget(self.line_3)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_17.addWidget(self.line_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.reg_nn_actvfunc_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.reg_nn_actvfunc_comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_nn_actvfunc_comboBox.setObjectName("reg_nn_actvfunc_comboBox")
        self.reg_nn_actvfunc_comboBox.addItem("")
        self.reg_nn_actvfunc_comboBox.addItem("")
        self.reg_nn_actvfunc_comboBox.addItem("")
        self.reg_nn_actvfunc_comboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.reg_nn_actvfunc_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.reg_nn_solver_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.reg_nn_solver_comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_nn_solver_comboBox.setObjectName("reg_nn_solver_comboBox")
        self.reg_nn_solver_comboBox.addItem("")
        self.reg_nn_solver_comboBox.addItem("")
        self.reg_nn_solver_comboBox.addItem("")
        self.horizontalLayout_11.addWidget(self.reg_nn_solver_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.reg_nn_learnrate_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.reg_nn_learnrate_comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_nn_learnrate_comboBox.setObjectName("reg_nn_learnrate_comboBox")
        self.reg_nn_learnrate_comboBox.addItem("")
        self.reg_nn_learnrate_comboBox.addItem("")
        self.reg_nn_learnrate_comboBox.addItem("")
        self.horizontalLayout_13.addWidget(self.reg_nn_learnrate_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_32.addWidget(self.label_41)
        self.reg_nn_val_percentage_horizontalSlider = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_val_percentage_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.reg_nn_val_percentage_horizontalSlider.setSizePolicy(sizePolicy)
        self.reg_nn_val_percentage_horizontalSlider.setMaximumSize(QtCore.QSize(170, 16777215))
        self.reg_nn_val_percentage_horizontalSlider.setMinimum(5)
        self.reg_nn_val_percentage_horizontalSlider.setMaximum(95)
        self.reg_nn_val_percentage_horizontalSlider.setProperty("value", 10)
        self.reg_nn_val_percentage_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.reg_nn_val_percentage_horizontalSlider.setObjectName("reg_nn_val_percentage_horizontalSlider")
        self.horizontalLayout_32.addWidget(self.reg_nn_val_percentage_horizontalSlider)
        self.clas_nn_val_percent_label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_val_percent_label.sizePolicy().hasHeightForWidth())
        self.clas_nn_val_percent_label.setSizePolicy(sizePolicy)
        self.clas_nn_val_percent_label.setMinimumSize(QtCore.QSize(35, 0))
        self.clas_nn_val_percent_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.clas_nn_val_percent_label.setBaseSize(QtCore.QSize(30, 0))
        self.clas_nn_val_percent_label.setObjectName("clas_nn_val_percent_label")
        self.horizontalLayout_32.addWidget(self.clas_nn_val_percent_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.reg_nn_max_iter_horizontalSlider = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_max_iter_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.reg_nn_max_iter_horizontalSlider.setSizePolicy(sizePolicy)
        self.reg_nn_max_iter_horizontalSlider.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_nn_max_iter_horizontalSlider.setMinimum(1)
        self.reg_nn_max_iter_horizontalSlider.setMaximum(300)
        self.reg_nn_max_iter_horizontalSlider.setProperty("value", 100)
        self.reg_nn_max_iter_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.reg_nn_max_iter_horizontalSlider.setObjectName("reg_nn_max_iter_horizontalSlider")
        self.horizontalLayout_15.addWidget(self.reg_nn_max_iter_horizontalSlider)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.reg_nn_max_iter_label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_max_iter_label.sizePolicy().hasHeightForWidth())
        self.reg_nn_max_iter_label.setSizePolicy(sizePolicy)
        self.reg_nn_max_iter_label.setMinimumSize(QtCore.QSize(35, 0))
        self.reg_nn_max_iter_label.setObjectName("reg_nn_max_iter_label")
        self.horizontalLayout_15.addWidget(self.reg_nn_max_iter_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.reg_nn_alpha_horizontalSlider = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_alpha_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.reg_nn_alpha_horizontalSlider.setSizePolicy(sizePolicy)
        self.reg_nn_alpha_horizontalSlider.setMaximumSize(QtCore.QSize(160, 16777215))
        self.reg_nn_alpha_horizontalSlider.setMinimum(1)
        self.reg_nn_alpha_horizontalSlider.setMaximum(100)
        self.reg_nn_alpha_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.reg_nn_alpha_horizontalSlider.setObjectName("reg_nn_alpha_horizontalSlider")
        self.horizontalLayout_16.addWidget(self.reg_nn_alpha_horizontalSlider)
        spacerItem6 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.reg_nn_alpha_label = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_alpha_label.sizePolicy().hasHeightForWidth())
        self.reg_nn_alpha_label.setSizePolicy(sizePolicy)
        self.reg_nn_alpha_label.setMinimumSize(QtCore.QSize(50, 0))
        self.reg_nn_alpha_label.setObjectName("reg_nn_alpha_label")
        self.horizontalLayout_16.addWidget(self.reg_nn_alpha_label)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addLayout(self.verticalLayout_8)
        self.regression_parameters_stackedWidget.addWidget(self.nn_regression_page)
        self.svm_regression_page = QtWidgets.QWidget()
        self.svm_regression_page.setObjectName("svm_regression_page")
        self.label_3 = QtWidgets.QLabel(self.svm_regression_page)
        self.label_3.setGeometry(QtCore.QRect(210, 90, 60, 16))
        self.label_3.setObjectName("label_3")
        self.regression_parameters_stackedWidget.addWidget(self.svm_regression_page)
        self.randomforest_regression_page = QtWidgets.QWidget()
        self.randomforest_regression_page.setObjectName("randomforest_regression_page")
        self.label_6 = QtWidgets.QLabel(self.randomforest_regression_page)
        self.label_6.setGeometry(QtCore.QRect(190, 120, 60, 16))
        self.label_6.setObjectName("label_6")
        self.regression_parameters_stackedWidget.addWidget(self.randomforest_regression_page)
        self.gradientboosting_regression_page = QtWidgets.QWidget()
        self.gradientboosting_regression_page.setObjectName("gradientboosting_regression_page")
        self.label_7 = QtWidgets.QLabel(self.gradientboosting_regression_page)
        self.label_7.setGeometry(QtCore.QRect(200, 180, 60, 16))
        self.label_7.setObjectName("label_7")
        self.regression_parameters_stackedWidget.addWidget(self.gradientboosting_regression_page)
        self.horizontalLayout_9.addWidget(self.regression_parameters_stackedWidget)
        self.regression_and_classification_stackedWidget.addWidget(self.page_regression)
        self.page_classification = QtWidgets.QWidget()
        self.page_classification.setObjectName("page_classification")
        self.layoutWidget2 = QtWidgets.QWidget(self.page_classification)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, -10, 921, 431))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.nn_classification_radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.nn_classification_radioButton.setObjectName("nn_classification_radioButton")
        self.verticalLayout_10.addWidget(self.nn_classification_radioButton)
        self.svm_classification_radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.svm_classification_radioButton.setObjectName("svm_classification_radioButton")
        self.verticalLayout_10.addWidget(self.svm_classification_radioButton)
        self.randomforest_classification_radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.randomforest_classification_radioButton.setObjectName("randomforest_classification_radioButton")
        self.verticalLayout_10.addWidget(self.randomforest_classification_radioButton)
        self.gradientboosting_classification_radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.gradientboosting_classification_radioButton.setObjectName("gradientboosting_classification_radioButton")
        self.verticalLayout_10.addWidget(self.gradientboosting_classification_radioButton)
        self.knn_classification_radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.knn_classification_radioButton.setObjectName("knn_classification_radioButton")
        self.verticalLayout_10.addWidget(self.knn_classification_radioButton)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_10.addWidget(self.line_5)
        self.classification_parameters_stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget2)
        self.classification_parameters_stackedWidget.setObjectName("classification_parameters_stackedWidget")
        self.nn_classification_page = QtWidgets.QWidget()
        self.nn_classification_page.setObjectName("nn_classification_page")
        self.layoutWidget_2 = QtWidgets.QWidget(self.nn_classification_page)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 10, 721, 381))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.clas_nn_hidden_layers_label = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_hidden_layers_label.sizePolicy().hasHeightForWidth())
        self.clas_nn_hidden_layers_label.setSizePolicy(sizePolicy)
        self.clas_nn_hidden_layers_label.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clas_nn_hidden_layers_label.setObjectName("clas_nn_hidden_layers_label")
        self.verticalLayout_12.addWidget(self.clas_nn_hidden_layers_label)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.clas_nn_layers_horizontalSlider = QtWidgets.QSlider(self.layoutWidget_2)
        self.clas_nn_layers_horizontalSlider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.clas_nn_layers_horizontalSlider.setMinimum(1)
        self.clas_nn_layers_horizontalSlider.setMaximum(50)
        self.clas_nn_layers_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clas_nn_layers_horizontalSlider.setObjectName("clas_nn_layers_horizontalSlider")
        self.horizontalLayout_20.addWidget(self.clas_nn_layers_horizontalSlider)
        self.clas_nn_layers_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.clas_nn_layers_label.setObjectName("clas_nn_layers_label")
        self.horizontalLayout_20.addWidget(self.clas_nn_layers_label)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.clas_nn_layers_tableWidget = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.clas_nn_layers_tableWidget.setMaximumSize(QtCore.QSize(235, 16777215))
        self.clas_nn_layers_tableWidget.setObjectName("clas_nn_layers_tableWidget")
        self.clas_nn_layers_tableWidget.setColumnCount(1)
        self.clas_nn_layers_tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.clas_nn_layers_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clas_nn_layers_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.clas_nn_layers_tableWidget.setItem(0, 0, item)
        self.clas_nn_layers_tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout_12.addWidget(self.clas_nn_layers_tableWidget)
        self.horizontalLayout_18.addLayout(self.verticalLayout_12)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_18.addWidget(self.line_6)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_18.addWidget(self.line_7)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_21.addWidget(self.label_19)
        self.clas_nn_actvfunc_comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.clas_nn_actvfunc_comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clas_nn_actvfunc_comboBox.setObjectName("clas_nn_actvfunc_comboBox")
        self.clas_nn_actvfunc_comboBox.addItem("")
        self.clas_nn_actvfunc_comboBox.addItem("")
        self.clas_nn_actvfunc_comboBox.addItem("")
        self.clas_nn_actvfunc_comboBox.addItem("")
        self.horizontalLayout_21.addWidget(self.clas_nn_actvfunc_comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_22.addWidget(self.label_20)
        self.clas_nn_solver_comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.clas_nn_solver_comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clas_nn_solver_comboBox.setObjectName("clas_nn_solver_comboBox")
        self.clas_nn_solver_comboBox.addItem("")
        self.clas_nn_solver_comboBox.addItem("")
        self.clas_nn_solver_comboBox.addItem("")
        self.horizontalLayout_22.addWidget(self.clas_nn_solver_comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        self.clas_nn_learnrate_comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.clas_nn_learnrate_comboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clas_nn_learnrate_comboBox.setObjectName("clas_nn_learnrate_comboBox")
        self.clas_nn_learnrate_comboBox.addItem("")
        self.clas_nn_learnrate_comboBox.addItem("")
        self.clas_nn_learnrate_comboBox.addItem("")
        self.horizontalLayout_23.addWidget(self.clas_nn_learnrate_comboBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_31.addWidget(self.label_40)
        self.clas_nn_val_percentage_horizontalSlider = QtWidgets.QSlider(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_val_percentage_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.clas_nn_val_percentage_horizontalSlider.setSizePolicy(sizePolicy)
        self.clas_nn_val_percentage_horizontalSlider.setMaximumSize(QtCore.QSize(170, 16777215))
        self.clas_nn_val_percentage_horizontalSlider.setMinimum(5)
        self.clas_nn_val_percentage_horizontalSlider.setMaximum(95)
        self.clas_nn_val_percentage_horizontalSlider.setProperty("value", 10)
        self.clas_nn_val_percentage_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clas_nn_val_percentage_horizontalSlider.setObjectName("clas_nn_val_percentage_horizontalSlider")
        self.horizontalLayout_31.addWidget(self.clas_nn_val_percentage_horizontalSlider)
        self.reg_nn_val_percent_label = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_nn_val_percent_label.sizePolicy().hasHeightForWidth())
        self.reg_nn_val_percent_label.setSizePolicy(sizePolicy)
        self.reg_nn_val_percent_label.setMinimumSize(QtCore.QSize(35, 0))
        self.reg_nn_val_percent_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.reg_nn_val_percent_label.setBaseSize(QtCore.QSize(30, 0))
        self.reg_nn_val_percent_label.setObjectName("reg_nn_val_percent_label")
        self.horizontalLayout_31.addWidget(self.reg_nn_val_percent_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        self.clas_nn_max_iter_horizontalSlider = QtWidgets.QSlider(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_max_iter_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.clas_nn_max_iter_horizontalSlider.setSizePolicy(sizePolicy)
        self.clas_nn_max_iter_horizontalSlider.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clas_nn_max_iter_horizontalSlider.setMinimum(1)
        self.clas_nn_max_iter_horizontalSlider.setMaximum(300)
        self.clas_nn_max_iter_horizontalSlider.setPageStep(1)
        self.clas_nn_max_iter_horizontalSlider.setProperty("value", 100)
        self.clas_nn_max_iter_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clas_nn_max_iter_horizontalSlider.setObjectName("clas_nn_max_iter_horizontalSlider")
        self.horizontalLayout_25.addWidget(self.clas_nn_max_iter_horizontalSlider)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.clas_nn_max_iter_label = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_max_iter_label.sizePolicy().hasHeightForWidth())
        self.clas_nn_max_iter_label.setSizePolicy(sizePolicy)
        self.clas_nn_max_iter_label.setMinimumSize(QtCore.QSize(35, 0))
        self.clas_nn_max_iter_label.setObjectName("clas_nn_max_iter_label")
        self.horizontalLayout_25.addWidget(self.clas_nn_max_iter_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_26.addWidget(self.label_23)
        self.clas_nn_alpha_horizontalSlider = QtWidgets.QSlider(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_alpha_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.clas_nn_alpha_horizontalSlider.setSizePolicy(sizePolicy)
        self.clas_nn_alpha_horizontalSlider.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clas_nn_alpha_horizontalSlider.setMinimum(1)
        self.clas_nn_alpha_horizontalSlider.setMaximum(100)
        self.clas_nn_alpha_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.clas_nn_alpha_horizontalSlider.setObjectName("clas_nn_alpha_horizontalSlider")
        self.horizontalLayout_26.addWidget(self.clas_nn_alpha_horizontalSlider)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem8)
        self.clas_nn_alpha_label = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clas_nn_alpha_label.sizePolicy().hasHeightForWidth())
        self.clas_nn_alpha_label.setSizePolicy(sizePolicy)
        self.clas_nn_alpha_label.setMinimumSize(QtCore.QSize(50, 0))
        self.clas_nn_alpha_label.setObjectName("clas_nn_alpha_label")
        self.horizontalLayout_26.addWidget(self.clas_nn_alpha_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.classification_parameters_stackedWidget.addWidget(self.nn_classification_page)
        self.svm_classification_page = QtWidgets.QWidget()
        self.svm_classification_page.setObjectName("svm_classification_page")
        self.label_10 = QtWidgets.QLabel(self.svm_classification_page)
        self.label_10.setGeometry(QtCore.QRect(260, 130, 60, 16))
        self.label_10.setObjectName("label_10")
        self.classification_parameters_stackedWidget.addWidget(self.svm_classification_page)
        self.randomforest_classification_page = QtWidgets.QWidget()
        self.randomforest_classification_page.setObjectName("randomforest_classification_page")
        self.label_9 = QtWidgets.QLabel(self.randomforest_classification_page)
        self.label_9.setGeometry(QtCore.QRect(100, 120, 60, 16))
        self.label_9.setObjectName("label_9")
        self.classification_parameters_stackedWidget.addWidget(self.randomforest_classification_page)
        self.gradientboosting_classification_page = QtWidgets.QWidget()
        self.gradientboosting_classification_page.setObjectName("gradientboosting_classification_page")
        self.label_12 = QtWidgets.QLabel(self.gradientboosting_classification_page)
        self.label_12.setGeometry(QtCore.QRect(160, 150, 60, 16))
        self.label_12.setObjectName("label_12")
        self.classification_parameters_stackedWidget.addWidget(self.gradientboosting_classification_page)
        self.knn_classification_page = QtWidgets.QWidget()
        self.knn_classification_page.setObjectName("knn_classification_page")
        self.label_13 = QtWidgets.QLabel(self.knn_classification_page)
        self.label_13.setGeometry(QtCore.QRect(240, 170, 60, 16))
        self.label_13.setObjectName("label_13")
        self.classification_parameters_stackedWidget.addWidget(self.knn_classification_page)
        self.horizontalLayout_10.addWidget(self.classification_parameters_stackedWidget)
        self.regression_and_classification_stackedWidget.addWidget(self.page_classification)
        self.verticalLayout_7.addWidget(self.regression_and_classification_stackedWidget)
        self.tabs_widget.addTab(self.model_selection_tab, "")
        self.inputoutput_tab = QtWidgets.QWidget()
        self.inputoutput_tab.setObjectName("inputoutput_tab")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.inputoutput_tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 20, 921, 421))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.available_columns_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.available_columns_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.available_columns_listWidget.setObjectName("available_columns_listWidget")
        self.verticalLayout_2.addWidget(self.available_columns_listWidget)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_input_columns_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.add_input_columns_pushButton.setObjectName("add_input_columns_pushButton")
        self.horizontalLayout.addWidget(self.add_input_columns_pushButton)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.input_columns_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.input_columns_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.input_columns_listWidget.setObjectName("input_columns_listWidget")
        self.verticalLayout_3.addWidget(self.input_columns_listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.remove_input_columns_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.remove_input_columns_pushButton.setObjectName("remove_input_columns_pushButton")
        self.horizontalLayout_2.addWidget(self.remove_input_columns_pushButton)
        self.clear_input_columns_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.clear_input_columns_pushButton.setObjectName("clear_input_columns_pushButton")
        self.horizontalLayout_2.addWidget(self.clear_input_columns_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_output_columns_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.add_output_columns_pushButton.setObjectName("add_output_columns_pushButton")
        self.horizontalLayout_3.addWidget(self.add_output_columns_pushButton)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.output_columns_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.output_columns_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.output_columns_listWidget.setObjectName("output_columns_listWidget")
        self.verticalLayout_6.addWidget(self.output_columns_listWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.remove_output_columns_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.remove_output_columns_pushButton.setObjectName("remove_output_columns_pushButton")
        self.horizontalLayout_4.addWidget(self.remove_output_columns_pushButton)
        self.clear_output_columns_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.clear_output_columns_pushButton.setObjectName("clear_output_columns_pushButton")
        self.horizontalLayout_4.addWidget(self.clear_output_columns_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.tabs_widget.addTab(self.inputoutput_tab, "")
        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.model_train_widget = MplWidget(self.train_tab)
        self.model_train_widget.setGeometry(QtCore.QRect(450, 20, 511, 401))
        self.model_train_widget.setObjectName("model_train_widget")
        self.widget = QtWidgets.QWidget(self.model_train_widget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 511, 401))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 1, 0, 1, 1)
        self.loading_widget = QtWaitingSpinner(self.widget)
        self.loading_widget.setObjectName("loading_widget")
        self.gridLayout_4.addWidget(self.loading_widget, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 1, 1, 1)
        self.train_metrics_stackedWidget = QtWidgets.QStackedWidget(self.train_tab)
        self.train_metrics_stackedWidget.setGeometry(QtCore.QRect(30, 300, 396, 181))
        self.train_metrics_stackedWidget.setMaximumSize(QtCore.QSize(16777215, 190))
        self.train_metrics_stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.train_metrics_stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.train_metrics_stackedWidget.setLineWidth(1)
        self.train_metrics_stackedWidget.setObjectName("train_metrics_stackedWidget")
        self.regression_metrics = QtWidgets.QWidget()
        self.regression_metrics.setObjectName("regression_metrics")
        self.layoutWidget3 = QtWidgets.QWidget(self.regression_metrics)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 261, 161))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 5, 0, 1, 1)
        self.reg_mse_label = QtWidgets.QLabel(self.layoutWidget3)
        self.reg_mse_label.setObjectName("reg_mse_label")
        self.gridLayout_2.addWidget(self.reg_mse_label, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 4, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 3, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem13, 1, 0, 1, 1)
        self.reg_rmse_label = QtWidgets.QLabel(self.layoutWidget3)
        self.reg_rmse_label.setObjectName("reg_rmse_label")
        self.gridLayout_2.addWidget(self.reg_rmse_label, 3, 1, 1, 1)
        self.reg_r2_label = QtWidgets.QLabel(self.layoutWidget3)
        self.reg_r2_label.setObjectName("reg_r2_label")
        self.gridLayout_2.addWidget(self.reg_r2_label, 4, 1, 1, 1)
        self.reg_max_error_label = QtWidgets.QLabel(self.layoutWidget3)
        self.reg_max_error_label.setObjectName("reg_max_error_label")
        self.gridLayout_2.addWidget(self.reg_max_error_label, 5, 1, 1, 1)
        self.train_metrics_stackedWidget.addWidget(self.regression_metrics)
        self.classification_metrics = QtWidgets.QWidget()
        self.classification_metrics.setObjectName("classification_metrics")
        self.layoutWidget_3 = QtWidgets.QWidget(self.classification_metrics)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 261, 161))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 5, 0, 1, 1)
        self.clas_accuracy_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.clas_accuracy_label.setObjectName("clas_accuracy_label")
        self.gridLayout_3.addWidget(self.clas_accuracy_label, 2, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 3, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem14, 1, 0, 1, 1)
        self.clas_recall_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.clas_recall_label.setObjectName("clas_recall_label")
        self.gridLayout_3.addWidget(self.clas_recall_label, 3, 1, 1, 1)
        self.clas_precision_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.clas_precision_label.setObjectName("clas_precision_label")
        self.gridLayout_3.addWidget(self.clas_precision_label, 4, 1, 1, 1)
        self.clas_f1_score_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.clas_f1_score_label.setObjectName("clas_f1_score_label")
        self.gridLayout_3.addWidget(self.clas_f1_score_label, 5, 1, 1, 1)
        self.train_metrics_stackedWidget.addWidget(self.classification_metrics)
        self.export_model_pushButton = QtWidgets.QPushButton(self.train_tab)
        self.export_model_pushButton.setGeometry(QtCore.QRect(700, 450, 169, 32))
        self.export_model_pushButton.setObjectName("export_model_pushButton")
        self.layoutWidget4 = QtWidgets.QWidget(self.train_tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 260, 403, 32))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem15 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem15)
        self.train_model_pushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.train_model_pushButton.setObjectName("train_model_pushButton")
        self.horizontalLayout_28.addWidget(self.train_model_pushButton)
        spacerItem16 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem16)
        self.layoutWidget5 = QtWidgets.QWidget(self.train_tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 30, 411, 155))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_30.addWidget(self.label_33)
        self.train_percentage_horizontalSlider = QtWidgets.QSlider(self.layoutWidget5)
        self.train_percentage_horizontalSlider.setMaximumSize(QtCore.QSize(170, 16777215))
        self.train_percentage_horizontalSlider.setMinimum(5)
        self.train_percentage_horizontalSlider.setMaximum(95)
        self.train_percentage_horizontalSlider.setProperty("value", 85)
        self.train_percentage_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.train_percentage_horizontalSlider.setObjectName("train_percentage_horizontalSlider")
        self.horizontalLayout_30.addWidget(self.train_percentage_horizontalSlider)
        self.train_percentage_label = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_percentage_label.sizePolicy().hasHeightForWidth())
        self.train_percentage_label.setSizePolicy(sizePolicy)
        self.train_percentage_label.setMinimumSize(QtCore.QSize(35, 0))
        self.train_percentage_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.train_percentage_label.setBaseSize(QtCore.QSize(30, 0))
        self.train_percentage_label.setObjectName("train_percentage_label")
        self.horizontalLayout_30.addWidget(self.train_percentage_label)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_29.addWidget(self.label_34)
        self.test_percentage_horizontalSlider = QtWidgets.QSlider(self.layoutWidget5)
        self.test_percentage_horizontalSlider.setMaximumSize(QtCore.QSize(170, 16777215))
        self.test_percentage_horizontalSlider.setMinimum(5)
        self.test_percentage_horizontalSlider.setMaximum(95)
        self.test_percentage_horizontalSlider.setProperty("value", 15)
        self.test_percentage_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.test_percentage_horizontalSlider.setObjectName("test_percentage_horizontalSlider")
        self.horizontalLayout_29.addWidget(self.test_percentage_horizontalSlider)
        self.test_percentage_label = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_percentage_label.sizePolicy().hasHeightForWidth())
        self.test_percentage_label.setSizePolicy(sizePolicy)
        self.test_percentage_label.setMinimumSize(QtCore.QSize(35, 0))
        self.test_percentage_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.test_percentage_label.setBaseSize(QtCore.QSize(30, 0))
        self.test_percentage_label.setObjectName("test_percentage_label")
        self.horizontalLayout_29.addWidget(self.test_percentage_label)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        spacerItem17 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.shuffle_samples_checkBox = QtWidgets.QCheckBox(self.layoutWidget5)
        self.shuffle_samples_checkBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.shuffle_samples_checkBox.setText("")
        self.shuffle_samples_checkBox.setObjectName("shuffle_samples_checkBox")
        self.horizontalLayout_14.addWidget(self.shuffle_samples_checkBox)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.verticalLayout_14.addLayout(self.horizontalLayout_14)
        self.layoutWidget6 = QtWidgets.QWidget(self.train_tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 190, 391, 58))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 0, 1, 1, 1)
        self.train_dataset_shape_label = QtWidgets.QLabel(self.layoutWidget6)
        self.train_dataset_shape_label.setObjectName("train_dataset_shape_label")
        self.gridLayout.addWidget(self.train_dataset_shape_label, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 1, 1, 1, 1)
        self.test_dataset_shape_label = QtWidgets.QLabel(self.layoutWidget6)
        self.test_dataset_shape_label.setObjectName("test_dataset_shape_label")
        self.gridLayout.addWidget(self.test_dataset_shape_label, 1, 2, 1, 1)
        self.loading_widget_2 = QtWaitingSpinner(self.train_tab)
        self.loading_widget_2.setGeometry(QtCore.QRect(530, 410, 20, 20))
        self.loading_widget_2.setObjectName("loading_widget_2")
        self.tabs_widget.addTab(self.train_tab, "")
        self.test_tab = QtWidgets.QWidget()
        self.test_tab.setObjectName("test_tab")
        self.tabs_widget.addTab(self.test_tab, "")

        self.retranslateUi(Dialog)
        self.tabs_widget.setCurrentIndex(5)
        self.pre_process_replacing_stackedWidget.setCurrentIndex(1)
        self.pre_process_filtering_stackedWidget.setCurrentIndex(1)
        self.regression_and_classification_stackedWidget.setCurrentIndex(1)
        self.regression_parameters_stackedWidget.setCurrentIndex(0)
        self.classification_parameters_stackedWidget.setCurrentIndex(0)
        self.train_metrics_stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Machine Learning Generic Modeller"))
        self.load_file_pushButton.setText(_translate("Dialog", "Load File"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.dataset_load_tab), _translate("Dialog", "Dataset Load"))
        self.plot_radioButton.setText(_translate("Dialog", "Plot"))
        self.boxplot_radioButton.setText(_translate("Dialog", "Boxplot"))
        self.histogram_radioButton.setText(_translate("Dialog", "Histogram"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.visualise_tab), _translate("Dialog", "Visualise"))
        self.numeric_scaling_checkBox.setText(_translate("Dialog", "Numeric Scaling "))
        self.remove_duplicates_checkBox.setText(_translate("Dialog", "Remove Dulpicate"))
        self.remove_outliers_checkBox.setText(_translate("Dialog", "Remove Outliers"))
        self.outliers_treshold_label.setText(_translate("Dialog", "2.0"))
        self.treshold_sigma_label.setText(_translate("Dialog", " σ"))
        self.replace_values_checkBox.setText(_translate("Dialog", "Replace Values"))
        self.label_in.setText(_translate("Dialog", "in"))
        self.label_with.setText(_translate("Dialog", "with"))
        self.filter_values_checkBox.setText(_translate("Dialog", "Filter Out"))
        self.filter_operator_comboBox.setItemText(0, _translate("Dialog", "Equal"))
        self.filter_operator_comboBox.setItemText(1, _translate("Dialog", "Not equal"))
        self.filter_operator_comboBox.setItemText(2, _translate("Dialog", "Less than"))
        self.filter_operator_comboBox.setItemText(3, _translate("Dialog", "Less than or equal to"))
        self.filter_operator_comboBox.setItemText(4, _translate("Dialog", "Greater than"))
        self.filter_operator_comboBox.setItemText(5, _translate("Dialog", "Greater than or equal to"))
        self.addrule_filter_value_pushButton.setText(_translate("Dialog", "Add Rule"))
        self.addrule_replace_value_pushButton.setText(_translate("Dialog", "Add Rule"))
        self.label_in_2.setText(_translate("Dialog", "Replacing Rules"))
        self.label_in_3.setText(_translate("Dialog", "Filtering Rules"))
        self.remove_replace_value_pushButton.setText(_translate("Dialog", "Remove Selected"))
        self.clear_replace_value_pushButton.setText(_translate("Dialog", "Clear"))
        self.remove_filter_rule_pushButton.setText(_translate("Dialog", "Remove Selected"))
        self.clear_filter_rule_pushButton.setText(_translate("Dialog", "Clear"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.pre_process_tab), _translate("Dialog", "Pre-Process"))
        self.regression_selection_radioButton.setText(_translate("Dialog", "Regression"))
        self.classification_selection_radioButton.setText(_translate("Dialog", "Classification"))
        self.nn_regression_radioButton.setText(_translate("Dialog", "Neural Networks"))
        self.svm_regression_radioButton.setText(_translate("Dialog", "Support Vector Machine"))
        self.randomforest_regression_radioButton.setText(_translate("Dialog", "Random Forest"))
        self.gradientboosting_regression_radioButton.setText(_translate("Dialog", "Gradient Boosting"))
        self.reg_nn_hidden_layers_label.setText(_translate("Dialog", "Number of Hidden Layers"))
        self.reg_nn_layers_label.setText(_translate("Dialog", "1"))
        item = self.reg_nn_layers_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Hidden Layer 1"))
        item = self.reg_nn_layers_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Number Of Neurons"))
        __sortingEnabled = self.reg_nn_layers_tableWidget.isSortingEnabled()
        self.reg_nn_layers_tableWidget.setSortingEnabled(False)
        item = self.reg_nn_layers_tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "10"))
        self.reg_nn_layers_tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_16.setText(_translate("Dialog", "Activation Function"))
        self.reg_nn_actvfunc_comboBox.setItemText(0, _translate("Dialog", "relu"))
        self.reg_nn_actvfunc_comboBox.setItemText(1, _translate("Dialog", "identity"))
        self.reg_nn_actvfunc_comboBox.setItemText(2, _translate("Dialog", "logistic"))
        self.reg_nn_actvfunc_comboBox.setItemText(3, _translate("Dialog", "tanh"))
        self.label_17.setText(_translate("Dialog", "Solver"))
        self.reg_nn_solver_comboBox.setItemText(0, _translate("Dialog", "adam"))
        self.reg_nn_solver_comboBox.setItemText(1, _translate("Dialog", "lbfgs"))
        self.reg_nn_solver_comboBox.setItemText(2, _translate("Dialog", "sgd"))
        self.label_18.setText(_translate("Dialog", "Learning Rate"))
        self.reg_nn_learnrate_comboBox.setItemText(0, _translate("Dialog", "constant"))
        self.reg_nn_learnrate_comboBox.setItemText(1, _translate("Dialog", "invscaling"))
        self.reg_nn_learnrate_comboBox.setItemText(2, _translate("Dialog", "adaptive"))
        self.label_41.setText(_translate("Dialog", "Validation Percentage"))
        self.clas_nn_val_percent_label.setText(_translate("Dialog", "10%"))
        self.label.setText(_translate("Dialog", "Max Iterations"))
        self.reg_nn_max_iter_label.setText(_translate("Dialog", "100"))
        self.label_15.setText(_translate("Dialog", "Alpha"))
        self.reg_nn_alpha_label.setText(_translate("Dialog", "0.0001"))
        self.label_3.setText(_translate("Dialog", "SVM"))
        self.label_6.setText(_translate("Dialog", "Random"))
        self.label_7.setText(_translate("Dialog", "Boost"))
        self.nn_classification_radioButton.setText(_translate("Dialog", "Neural Networks"))
        self.svm_classification_radioButton.setText(_translate("Dialog", "Support Vector Machine"))
        self.randomforest_classification_radioButton.setText(_translate("Dialog", "Random Forest"))
        self.gradientboosting_classification_radioButton.setText(_translate("Dialog", "Gradient Tree Boosting"))
        self.knn_classification_radioButton.setText(_translate("Dialog", "K-Nearest Neighbours"))
        self.clas_nn_hidden_layers_label.setText(_translate("Dialog", "Number of Hidden Layers"))
        self.clas_nn_layers_label.setText(_translate("Dialog", "1"))
        item = self.clas_nn_layers_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Hidden Layer 1"))
        item = self.clas_nn_layers_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Number Of Neurons"))
        __sortingEnabled = self.clas_nn_layers_tableWidget.isSortingEnabled()
        self.clas_nn_layers_tableWidget.setSortingEnabled(False)
        item = self.clas_nn_layers_tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "10"))
        self.clas_nn_layers_tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_19.setText(_translate("Dialog", "Activation Function"))
        self.clas_nn_actvfunc_comboBox.setItemText(0, _translate("Dialog", "relu"))
        self.clas_nn_actvfunc_comboBox.setItemText(1, _translate("Dialog", "identity"))
        self.clas_nn_actvfunc_comboBox.setItemText(2, _translate("Dialog", "logistic"))
        self.clas_nn_actvfunc_comboBox.setItemText(3, _translate("Dialog", "tanh"))
        self.label_20.setText(_translate("Dialog", "Solver"))
        self.clas_nn_solver_comboBox.setItemText(0, _translate("Dialog", "adam"))
        self.clas_nn_solver_comboBox.setItemText(1, _translate("Dialog", "lbfgs"))
        self.clas_nn_solver_comboBox.setItemText(2, _translate("Dialog", "sgd"))
        self.label_21.setText(_translate("Dialog", "Learning Rate"))
        self.clas_nn_learnrate_comboBox.setItemText(0, _translate("Dialog", "constant"))
        self.clas_nn_learnrate_comboBox.setItemText(1, _translate("Dialog", "invscaling"))
        self.clas_nn_learnrate_comboBox.setItemText(2, _translate("Dialog", "adaptive"))
        self.label_40.setText(_translate("Dialog", "Validation Percentage"))
        self.reg_nn_val_percent_label.setText(_translate("Dialog", "10%"))
        self.label_22.setText(_translate("Dialog", "Max Iterations"))
        self.clas_nn_max_iter_label.setText(_translate("Dialog", "100"))
        self.label_23.setText(_translate("Dialog", "Alpha"))
        self.clas_nn_alpha_label.setText(_translate("Dialog", "0.0001"))
        self.label_10.setText(_translate("Dialog", "SVM"))
        self.label_9.setText(_translate("Dialog", "Random"))
        self.label_12.setText(_translate("Dialog", "Boost"))
        self.label_13.setText(_translate("Dialog", "KNN"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.model_selection_tab), _translate("Dialog", "Model Selction"))
        self.label_2.setText(_translate("Dialog", "Available Columns"))
        self.add_input_columns_pushButton.setText(_translate("Dialog", ">"))
        self.label_4.setText(_translate("Dialog", "Inputs Columns"))
        self.remove_input_columns_pushButton.setText(_translate("Dialog", "Remove Selected"))
        self.clear_input_columns_pushButton.setText(_translate("Dialog", "Clear"))
        self.add_output_columns_pushButton.setText(_translate("Dialog", ">"))
        self.label_5.setText(_translate("Dialog", "Output Columns"))
        self.remove_output_columns_pushButton.setText(_translate("Dialog", "Remove Selected"))
        self.clear_output_columns_pushButton.setText(_translate("Dialog", "Clear"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.inputoutput_tab), _translate("Dialog", "Input/Output"))
        self.label_32.setText(_translate("Dialog", "Max Error"))
        self.reg_mse_label.setText(_translate("Dialog", "0"))
        self.label_30.setText(_translate("Dialog", "R2:"))
        self.label_29.setText(_translate("Dialog", "Mean Squared Error: "))
        self.label_25.setText(_translate("Dialog", "Regression Metrics"))
        self.label_31.setText(_translate("Dialog", "Root Mean Squared Error:"))
        self.reg_rmse_label.setText(_translate("Dialog", "0"))
        self.reg_r2_label.setText(_translate("Dialog", "0"))
        self.reg_max_error_label.setText(_translate("Dialog", "0"))
        self.label_36.setText(_translate("Dialog", "F1 Score:"))
        self.clas_accuracy_label.setText(_translate("Dialog", "0"))
        self.label_37.setText(_translate("Dialog", "Precision:"))
        self.label_38.setText(_translate("Dialog", "Accuracy: "))
        self.label_26.setText(_translate("Dialog", "Classification Metrics"))
        self.label_39.setText(_translate("Dialog", "Recall:"))
        self.clas_recall_label.setText(_translate("Dialog", "0"))
        self.clas_precision_label.setText(_translate("Dialog", "0"))
        self.clas_f1_score_label.setText(_translate("Dialog", "0"))
        self.export_model_pushButton.setText(_translate("Dialog", "Export Model"))
        self.train_model_pushButton.setText(_translate("Dialog", "Train  Model"))
        self.label_33.setText(_translate("Dialog", "Training Set Percentage"))
        self.train_percentage_label.setText(_translate("Dialog", "85%"))
        self.label_34.setText(_translate("Dialog", "Testing Set Percentage"))
        self.test_percentage_label.setText(_translate("Dialog", "15%"))
        self.label_8.setText(_translate("Dialog", "Shuffle Samples"))
        self.label_11.setText(_translate("Dialog", "Train Dataset Shape:"))
        self.train_dataset_shape_label.setText(_translate("Dialog", "99999 x 99999"))
        self.label_24.setText(_translate("Dialog", "Test Dataset Shape:"))
        self.test_dataset_shape_label.setText(_translate("Dialog", "99999 x 99999"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.train_tab), _translate("Dialog", "Train"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.test_tab), _translate("Dialog", "Test"))

from personalised_widgets import MplWidget, QtWaitingSpinner
import ml_gui_resources_rc
